import DS from 'ember-data';

export default DS.Model.extend({
  // community: DS.attr(),
  // formatQuantity: DS.attr('number'),
  // formats: DS.attr(),
  // labels: DS.hasMany('label'),
  // series: DS.attr(),
  // status: DS.attr('string'),
  // thumb: DS.attr(),
  artists: DS.attr(),
  // artists: DS.hasMany('artist', {async: true}),
  artistsSort: DS.attr('string'),
  companies: DS.attr(),
  country: DS.attr('string'),
  extraartists: DS.attr(),
  genres: DS.attr(),
  images: DS.attr(),
  labels: DS.attr(),
  lowestPrice: DS.attr('number'),
  mainRelease: DS.belongsTo('release', {async: true}),
  mainReleaseUrl: DS.attr('string'),
  masterId: DS.belongsTo('master'),
  masterUrl: DS.attr('string'),
  notes: DS.attr('string'),
  numForSale: DS.attr('number'),
  released: DS.attr('date'),
  releasedFormatted: DS.attr('string'),
  styles: DS.attr(),
  title: DS.attr('string'),
  tracklist: DS.attr(),
  uri: DS.attr('string'),
  videos: DS.attr(),
  year: DS.attr('number'),
});
